version: '3.8'

services:
  client:
    image: aleksandr3/coocking-db-client  
    depends_on:
      - server
    ports:
      - "80:80"  

  server:
    image: aleksandr3/coocking-db-server 
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mealapp
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mealapp
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

