version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"  # NGINX serving on port 80
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    expose:
      - "5000"  # Only expose internally, no external port mapping
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql  # Refers to the mysql service
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mealapp
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mealapp
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"  # Internal exposure, no external port mapping

volumes:
  mysql-data:
