# Use the official Node.js 16 image as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /app/server

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install   

# Copy the rest of the application code to the container
COPY . .

COPY mealapp.sql /app/server/mealapp.sql

# Expose port 5000 for the Express application
EXPOSE 5000

# Start the Express application
CMD ["npm", "start"]  
